// <auto-generated />
using System;
using AscensoresIruna.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AscensoresIruna.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AscensoresIruna.Api.Models.Elevator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Elevators");
                });

            modelBuilder.Entity("AscensoresIruna.Api.Models.ReporterIp", b =>
                {
                    b.Property<string>("IpAddressHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Confirmations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Contradictions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("TrustScore")
                        .HasColumnType("REAL");

                    b.HasKey("IpAddressHash");

                    b.ToTable("ReporterIps");
                });

            modelBuilder.Entity("AscensoresIruna.Api.Models.StatusReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElevatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddressHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ElevatorId", "ReportedAt");

                    b.HasIndex("IpAddressHash", "ElevatorId", "ReportedAt");

                    b.ToTable("StatusReports");
                });

            modelBuilder.Entity("AscensoresIruna.Api.Models.StatusReport", b =>
                {
                    b.HasOne("AscensoresIruna.Api.Models.Elevator", "Elevator")
                        .WithMany("StatusReports")
                        .HasForeignKey("ElevatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elevator");
                });

            modelBuilder.Entity("AscensoresIruna.Api.Models.Elevator", b =>
                {
                    b.Navigation("StatusReports");
                });
#pragma warning restore 612, 618
        }
    }
}
